create database customer_behavior;

use customer_behavior;

select * from customer;

-- Compared total revenue generated by male vs. female customers. 
select gender , sum(purchase_amount) as total_revenue
from customer
group by gender;

--  High-Spending Discount Users – Identify  customers who used discounts but still 
-- spent above the average purchase amount.  

select customer_id , purchase_amount
from customer 
where discount_applied="Yes" and 
purchase_amount >
(select avg(purchase_amount)
from customer);

-- Top 5 Products by Rating – Found products with the highest average review ratings. 
select item_purchased , avg(review_rating) as avg_rating 
from customer
group by item_purchased 
order by avg_rating desc
limit 5;


-- Compared average purchase amounts between Standard and Express shipping.
select shipping_type , avg(purchase_amount) as avg_amount
from customer 
where shipping_type in ("Express","Standard")
group by shipping_type ;

--   Compared average spend and total revenue  across subscription status.
select  subscription_status ,  count(customer_id) as total_customers , avg(purchase_amount) as avg_spend , 
sum(purchase_amount) as total_revenue 
from customer
group by subscription_status;

-- Discount-Dependent Products – Identified 5 products with the highest percentage of discounted purchases.
select item_purchased , 
100*sum(case when discount_applied="Yes" then 1 else 0 end)/count(*) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- customer Segmentation – Classified customers into New, Returning, and Loyal segments based on purchase history.
select purchase_history , count(previous_purchases) as count_of_purchases
from (
select * ,case when previous_purchases=1 then "New"
				when previous_purchases between 2 and 10 then "Returning"
                else "Loyal" end as Purchase_history
from customer ) as a 
group by purchase_history
order by count_of_purchases;

-- Top 3 Products per Category – Listed the most purchased products within each  category
with item_counts as 
(
 select category , item_purchased , count(customer_id) as total_count, 
 row_number() over(partition by category order by count(customer_id) desc) as item_rank 
 from customer
 group by category , item_purchased
)
select item_rank , category , item_purchased ,  total_count 
from item_counts
where item_rank <=3;

--  Repeat Buyers & Subscriptions – Checked whether customers with >5 purchases are more likely to subscribe. 
select subscription_status , count(customer_id) as repeat_buyers 
from customer 
where previous_purchases >5
group by subscription_status;

-- Calculated total revenue contribution of each age group.

select age_group , sum(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc;